language: node_js
node_js: stable
script:
  - npm run cover
after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"
notifications:
  email:
    on_success: never
    on_failure: change
